services:
  db:
    # image: postgis/postgis:12-2.5-alpine
    image: postgis/postgis:14-3.5-alpine
    # image: postgis/postgis:10-3.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - .:/home/user
    env_file:
      - .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.fastapi
    env_file:
      - .env
    ports:
      - '3002:3002'
    expose:
      - '3002'
    volumes:
      - ./fastapi:/code
      - ./tmp:/code/app/tmp
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 3002
  web:
    build: .
    command: sh ./start
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - '3001:3000'
    depends_on:
      - db
      - fastapi
      # - redis
    env_file:
      - .env
  # tfserving:
  #   image: tensorflow/serving:2.6.2
  #   ports:
  #     - '8500:8500'
  #     - '8501:8501'
  #   volumes:
  #     - ./models:/models
  #   environment:
  #     - MODEL_NAME=multi_conv_model
  # redis:
  #   image: redis:4.0-alpine
  #   command: redis-server --requirepass kyutech
  #   volumes:
  #     - redis:/data
  # sidekiq:
  #   depends_on:
  #     - db
  #     - redis
  #   build: .
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   volumes:
  #     - .:/app
  #     - bundle:/usr/local/bundle
  #   env_file:
  #     - .env
  # cable:
  #   depends_on:
  #     - redis
  #   build: .
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - 28080:28080
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
volumes:
  db:
  bundle:
  redis:
