source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.8'

gem 'rails', '~> 5.2.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'bootstrap', '~> 4.1.1'
gem 'jquery-rails'
gem 'simple_form'
gem 'devise'
gem 'activeadmin'
gem 'activeadmin_addons'
gem 'image_processing', '~> 1.2'
gem 'activestorage-validator'
gem 'state_machines-activerecord'
gem 'paper_trail'
gem 'font-awesome-sass', '~> 5.13.0'
gem 'leaflet-rails'

# gem 'activerecord-postgis-adapter'
# gem 'rgeo'
# gem 'rgeo-geojson'
gem 'active_model_serializers', '~> 0.10.0'
gem 'time_difference'

gem 'filterrific'
gem 'select2-rails'
gem 'will_paginate', '~> 3.1.0'

gem 'chartkick'
gem 'groupdate'
gem 'verbs'

# gem 'voltex'
# gem 'pundit'

gem 'devise_masquerade'
gem 'rack-cors'

gem 'rubyzip', '>= 1.2.1'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'wicked_pdf'

group :development, :test do
  gem 'rspec-rails', '~> 3.7'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers', '~> 3.1'
end

group :production do
  gem 'wkhtmltopdf-binary'
end

gem 'capistrano', '~> 3.7', '>= 3.7.1'
gem 'capistrano-rails', '~> 1.2'
gem 'capistrano-passenger', '>= 0.2.1'
gem 'capistrano-rvm'
gem 'capistrano-yarn'
gem 'dotenv-rails'
gem 'capistrano-rake', require: false
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'

gem 'nokogiri'
gem 'curb'
gem 'sidekiq'
gem 'whenever', require: false
# gem 'google_drive'
# gem 'jwt'
gem 'simple_command'

# gem "valid_email2"
gem 'bootstrap-datepicker-rails'
gem 'bootstrap4-datetime-picker-rails'

gem 'omniauth'
gem 'omniauth-garmin'